meatToVeg = {
    "meat": "tempeh",
    "chicken": "tofu",
    "duck": "seitan",
    "tuna": "jackfruit",
    "crab": "chickpeas",
    "krab": "chickpeas",
    "goose": "black lentil tofu",
    "turkey": "tofurkey",
    "beef": "tempeh",
    "steak": "portobello",
    "pork": "jackfruit",
    "lamb": "textured vegetable protein",
    "veal": "cauliflower",
    "bacon": "facon (tempeh)",
    "sausage": "seitan sausage",
    "buffalo": "seitan",
    "bison": "seitan",
    "elk": "gardein faux venison",
    "deer": "gardein faux venison",
    "venison": "gardein faux venison",
    "squid": "heart of palm",
    "calamari": "heart of palm",
    "sushi": "avocado",
    "salmon": "ground beet",
    "lox": "tomato",
    "shrimp": "sweet potato",
    "tilapia": "jackfruit",
    "salami": "seitan",
    "pastrami": "seitan",
    "pepperoni": "seitan",
    "ham": "tofu",
    "hot dog": "eggplant",
    "wurst": "seitan sausage",
    "prosciutto": "tofu",
    "spam": "tofu"
}

vegToMeat = {
    "seitan": "sausage",
    "tempeh": "beef",
    "jackfruit": "pork",
    "tofu": "chicken",
    "eggplant": "veal",
    "tofurkey": "turkey",
    "lentil": "ground beef",
    "chickpeas": "crab",
    "heart of palm": "squid",
    "textured vegetable protein": "lamb",
    "tvp": "lamb"
}